---
title: "R Notebook"
author: Jesse Bragger and Jett Vernaci
output: html_notebook
---
#1. 
We used the function quantile to find the five number summary of the data and then pulled out the 1st and 3rd quantiles from the output to find the IQR. 

```{r}
x <- c(2.2, 7.8, -4.4, 0.0, -1.2, 3.9, 4.9, -5.7, -7.9, -4.9, 28.7, 4.9)
Quant<-quantile(x)
Q1<-Quant[[2]]
Q3<-Quant[[4]]
IQR<-Q3-Q1
Q1
Q3
IQR
```
#2.
```{r}
#' This function calculates the first and third quartiles, and the interquartile range of a given sample.
#'
#' @param x This is the vector containing the sample
#'
#' @return The vector containing the first and third quartiles, and the interquartile range of the given sample
quartiles<-function(x){
Quant<-quantile(x)
Q1<-Quant[[2]]
Q3<-Quant[[4]]
IQR<-Q3-Q1
return(c(Q1=Q1,Q3=Q3,IQR=IQR))
}
quartiles(c(2.2, 7.8, -4.4, 0.0, -1.2, 3.9, 4.9, -5.7, -7.9, -4.9, 28.7, 4.9))
```
#3.
Yes there is one outlier since 28.7 is bigger than 19.0375 which is the upper limit.
```{r}
Q1-1.5*IQR
Q3+1.5*IQR
```
#4.
```{r}
#' This function takes a vector and determines whether or not an element of a set is an outlier using tukey's rule
#'
#' @param x a vector containing the sample 
#'
#' @return a boolean vector containing whether or not an element of the sample is an outlier or not
tukey.outlier <- function(x){
  quartiles(x)
  Outlier <- rep(NA, length(x))
  for(i in 1:length(x)){
    if(x[i]<Q1-1.5*IQR || x[i]>Q3+1.5*IQR){
      Outlier[i] <- TRUE
    }else{
  Outlier[i] <- FALSE
}
}
return(Outlier)
}
tukey.outlier(c(2.2, 7.8, -4.4, 0.0, -1.2, 3.9, 4.9, -5.7, -7.9, -4.9, 28.7, 4.9))
```

#5. 
```{r}
#' This tests an outlier function against the vector x to see if it is correctly identifying the outliers in the vector
#'
#' @param fun is the outlier function that is being tested
#'
#' @return A boolean that is true if the outlier function correctly identified the outliers and false if the function did not correctly identify the outliers 
test.tukey.outlier <- function(fun = tukey.outlier){
  x <- c(2.2, 7.8, -4.4, 0.0, -1.2, 3.9, 4.9, -5.7, -7.9, -4.9, 28.7, 4.9)
  OutlierTemplate <- c(FALSE ,FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,  TRUE, FALSE)

  if(sum(fun(x)==OutlierTemplate)==length(x)){
   return(TRUE)
  }else{
    return(FALSE)
}
}
test.tukey.outlier(tukey.outlier)
```

#6. 

```{r}
xnegative <- -x
tukey.outlier(xnegative)
```
Since 28.7 was an outlier in x, it would make sense that -28.7 would be the outlier in -x since the outlier boundaries would just get their sign switched. 

#7. 

```{r}
#' This tests an outlier function against the vector x and its negative to see if it is correctly identifying the outliers in the vectors
#'
#' @param fun is the outlier function that is being tested
#'
#' @return A boolean vector that is true if the outlier function correctly identified the outliers and false if the function did not correctly identify the outliers for both x and negative x
test.tukey.outlier <- function(fun = tukey.outlier){
  x <- c(2.2, 7.8, -4.4, 0.0, -1.2, 3.9, 4.9, -5.7, -7.9, -4.9, 28.7, 4.9)
  xnegative<- -x
  OutlierTemplate <- c(FALSE ,FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,  TRUE, FALSE)
  test.result <- rep(NA,2)
  if(sum(fun(x)==OutlierTemplate)==length(x)){
   test.result[1]<- TRUE
  }else{
    test.result[1] <- FALSE
  }
  if(sum(fun(xnegative)==OutlierTemplate)==length(xnegative)){
   test.result[2]<- TRUE
  }else{
    test.result[2] <- FALSE
  }
  return(test.result)
}
```


